packaging_format = 2

id = "wetty"
name = "Wetty"
description.en = "Terminal in browser over http/https"
description.fr = "Un terminal dans le navigateur sur http/https"

version = "2.7.0~ynh3"

maintainers = ["Salamandar"]

[upstream]
license = "MIT"
code = "https://github.com/butlerx/wetty"

[integration]
yunohost = ">=11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = false
disk = "50M"
ram.build = "700M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wetty"

    [install.init_main_permission]
    help.en = "Even if public, it still requires authentication."
    help.fr = "Même publique, vous devrez vous authentifier"
    type = "group"
    default = false

[resources]
    [resources.sources.main]
    url = "https://github.com/butlerx/wetty/archive/refs/tags/v2.7.0.tar.gz"
    sha256 = "4c920be38036da1edd2a01f16396ea095ec5fb3552a168caa0082a828ad87217"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
