#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wetty"
name = "Wetty"
description.en = "Terminal in browser over http/https"
description.fr = "Un terminal dans le navigateur sur http/https"

version = "3.0.4~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "MIT"
code = "https://github.com/butlerx/wetty"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = false

disk = "50M"
ram.build = "700M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wetty"

    [install.init_main_permission]
    help.en = "Even if public, it still requires authentication."
    help.fr = "Même publique, vous devrez vous authentifier"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/butlerx/wetty/archive/refs/tags/v3.0.4.tar.gz"
    sha256 = "e31e64c14439f5a1882ab0ec9477e1156eb3c47b22a35c365eaef082cb22a5b8"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "make, build-essential, python3, yarn"

    [resources.nodejs]
    version = "20"
