#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

# Install nodejs
ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring nginx web server..."

# Create a dedicated nginx config
ynh_config_add_nginx

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.json5" --destination="$install_dir/config.json5"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/config.json5"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/config.json5"

#=================================================
# BUILD YARN DEPENDENCIES
#=================================================
ynh_script_progression "Building Yarn dependencies... This may take several minutes for a first install."

pushd "$install_dir" || return 1
	 ; set "${node_load_PATH:?}"
	ynh_exec_as_app node_load_PATH" yarn
	ynh_exec_as_app node_load_PATH" yarn build
	ynh_exec_as_app node_load_PATH" yarn install --production --ignore-scripts --prefer-offline
	ynh_safe_rm "$install_dir/.cache"
popd || return 1

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring the systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Wetty Web Terminal service" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"  --wait_until="Server started"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
